"""Initial migration

Revision ID: 2c5a11af8a23
Revises: 
Create Date: 2026-07-11 19:56:07.666814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5a11af8a23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'course_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_constraint(op.f('courses_course_code_key'), 'courses', type_='unique')
    op.drop_index(op.f('idx_course_code'), table_name='courses')
    op.drop_column('courses', 'max_seats')
    op.alter_column('departments', 'dept_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('enrollments', 'grade',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.drop_index(op.f('idx_enrollment_student_course'), table_name='enrollments')
    op.drop_index(op.f('idx_null_grade'), table_name='enrollments', postgresql_where='(grade IS NULL)')
    op.alter_column('professors', 'prof_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('professors_email_key'), 'professors', type_='unique')
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('idx_students_enrollment_year'), table_name='students')
    op.drop_constraint(op.f('students_email_key'), 'students', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('students_email_key'), 'students', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_students_enrollment_year'), 'students', ['enrollment_year'], unique=False)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(op.f('professors_email_key'), 'professors', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('professors', 'prof_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('idx_null_grade'), 'enrollments', ['student_id'], unique=False, postgresql_where='(grade IS NULL)')
    op.create_index(op.f('idx_enrollment_student_course'), 'enrollments', ['student_id', 'course_id'], unique=True)
    op.alter_column('enrollments', 'grade',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=True)
    op.alter_column('departments', 'dept_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('courses', sa.Column('max_seats', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_course_code'), 'courses', ['course_code'], unique=False)
    op.create_unique_constraint(op.f('courses_course_code_key'), 'courses', ['course_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('courses', 'course_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
